
<?php require 'includes/config.php'; ?>
<?php include 'includes/header.php'; ?>
       
       <h1>Headline</h1>
       <p>Plaid deep v fashion axe, squid Schlitz Austin cray viral banjo kale chips. Austin ennui master cleanse crucifix. Direct trade lo-fi Austin, bitters Helvetica heirloom actually paleo High Life retro. Raw denim umami brunch whatever. Banjo readymade Austin single-origin coffee wayfarers ennui next level roof party YOLO, Shoreditch Etsy. Intelligentsia Helvetica Neutra, craft beer sartorial gastropub Cosby sweater semiotics fanny pack flannel flexitarian keytar raw denim scenester. Sartorial occupy YOLO, farm-to-table 90's Kickstarter Odd Future before they sold out Wes Anderson hoodie PBR&B American Apparel chambray tattooed twee.</p>
       
		<p>Shoreditch semiotics synth cold-pressed Pitchfork, ennui selvage mlkshk hoodie Brooklyn post-ironic fanny pack. Cornhole craft beer Blue Bottle, jean shorts bitters ethical cold-pressed wolf scenester swag forage next level photo booth art party. Vinyl Schlitz occupy pork belly street art, organic stumptown retro yr ethical messenger bag High Life. Actually Bushwick flexitarian, semiotics bicycle rights Shoreditch YOLO Godard dreamcatcher High Life post-ironic Vice narwhal XOXO 90's. Disrupt Echo Park Kickstarter yr. XOXO Banksy freegan, cardigan Godard keytar kitsch. Organic distillery flannel, vinyl Thundercats Austin Shoreditch kale chips cliche pork belly.</p>

		<p>Street art Etsy flexitarian organic hoodie +1, raw denim single-origin coffee bicycle rights butcher locavore flannel. Art party kale chips raw denim Brooklyn, YOLO chillwave Cosby sweater tote bag Godard paleo beard. Kale chips mustache Tumblr wolf, farm-to-table lo-fi brunch gluten-free artisan XOXO 8-bit drinking vinegar. Bicycle rights wayfarers post-ironic lomo church-key, vinyl Intelligentsia banjo stumptown Austin. VHS Vice blog skateboard, sriracha Williamsburg Echo Park messenger bag DIY 90's tousled meditation irony. Banh mi 3 wolf moon fap, letterpress you probably haven't heard of them gentrify hashtag twee. Taxidermy gentrify try-hard, skateboard tote bag keffiyeh tousled.</p> 
        
<?php include 'includes/footer.php' ;?>